### ISSUE TITLE
Can't create badges

### ISSUE THREAD

**Issue by drashti4** [mozilla/badges.mozilla.org#125]
https://badges.mozilla.org/en-US/badges/create doesn't work.

**Comment by martinsam** [comment]
http://badg.us/en-US/badges/create doesn't work

**Comment by lmorchard** [comment]
@drashti4 Do you have any more details? What doesn't work / how doesn't it work?

@martinsam This is badges.mozilla.org - badg.us is a different site under different managment

**Comment by lmorchard** [comment]
Works for me. Feel free to reopen with more specifics to reproduce the issue

**Comment by martinsam** [comment]
The page is  blank (No HTML)

**Comment by lmorchard** [comment]
Are you a vouched Mozillian? This page only works for users with vouched status on mozillians.org. Might be an issue with the error message

**Comment by martinsam** [comment]
In this case an error message can be useful
