### ISSUE TITLE
CSRF error on login

### ISSUE THREAD

**Issue by ianb** [mozilla/badges.mozilla.org#17]
I ended up at this page: https://badges.mozilla.org/en-US/browserid/browserid/verify/ – with a 403 message "CSRF verification failed. Request aborted."

My actions before: go to a badge claim page, logout, get redirected to home page, log back in (different email). In the end I seemed to have been logged in.

Successful attempt to reproduce: on home page log in, log out, log in again.

**Comment by lmorchard** [comment]
Will try to keep an eye out for this issue, but I can't reproduce it. At least, not with various combinations of signing in places with persona. I have seen CSRF errors when memcache fails, though. But, that should hopefully be a transient infra issue
