### ISSUE TITLE
'More...' link on a specific badge award shows *all* awards, not just that badge's.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/badges.mozilla.org#68]
https://badges.mozilla.org/en-US/badges/badge/You-closed-the-tree/awards

This link should show me all awards of the 'You closed the tree' badge, but instead shows me all badge awards ever, all ~2800 pages of them.

**Comment by federicoculloca** [comment]
Sorry for necro-posting, but has this been pushed to production? It seems the problem is still there https://badges.mozilla.org/en-US/badges/badge/MDN-Star/awards . See also #129.
