### ISSUE TITLE
Missing created badges

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/badges.mozilla.org#82]
I used to have some created badges for FOSDEM 2013:
http://badg.us/en-US/badges/badge/Mozilla_Devroom_Speaker-Fosdem_2013
http://badg.us/en-US/badges/badge/Mozilla_Devroom_Attendee-Fosdem_2013
http://badg.us/en-US/badges/badge/Mozilla_Booth-Fosdem_2013

I am not seeing them anymore.

**Comment by lmorchard** [comment]
badges.mozilla.org is a different site than badg.us, not sure who's managing badg.us these days.
