### ISSUE TITLE
Pil is deprecated(belongs to django-badger)

### ISSUE THREAD

**Issue by thechunsik** [mozilla/badges.mozilla.org#86]
Pil 1.1.7 is forked to Pillow 2.2.1.

I've sent [pull request to django-badger](https://github.com/mozilla/django-badger/pull/201/files), but users should fix it manually to build before that pull request is accepted.

**Comment by lmorchard** [comment]
This was fixed here: https://github.com/mozilla/badges.mozilla.org/commit/c3f1d4fc4b50aaac42031730efc7a8c625fd1c13
