### ISSUE TITLE
Awarded badge missing in profile

### ISSUE THREAD

**Issue by gaby2300** [mozilla/badges.mozilla.org#88]
I was awarded the Mozilla Summit 2013 badge sometime last year but it's missing in my profile:
https://badges.mozilla.org/en-US/profiles/profile/gmontagu. It was there the last time I checked but it's missing now. 

If I can do something to solve the issue, please tell me. If not, please do whatever it takes to solve it, aka make it show up again!

Thanks!

**Comment by lmorchard** [comment]
Hmm, it looks like that badge no longer exists. I think someone might have deleted it, which would have removed it for everyone

**Comment by gaby2300** [comment]
I'm sorry but I don't understand why it was removed!  Has it been removed in all backpacks? Would it possible to get it back again?

**Comment by lmorchard** [comment]
I'm not sure. In fact, I don't think that badge was ever issued from badges.mozilla.org. It looks like maybe it came from badger.openbadges.org? That's a different site from this one.

**Comment by gaby2300** [comment]
Don't worry, I've solved the problem!
I checked my backpack again and this badge was there! Some others were missing but I managed to search for the emails that awarded them to me so I added them again.

Many thanks for trying to help me!
